// these countries dont have daily data
export const excludeList = [
  "Anguilla",
  "Aruba",
  "Bermuda",
  "British Virgin Islands",
  "Caribbean Netherlands",
  "Cayman Islands",
  "Channel Islands",
  "Curaçao",
  "Diamond Princess",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "French Guiana",
  "French Polynesia",
  "Gibraltar",
  "Greenland",
  "Guadeloupe",
  "Holy See (Vatican City State)",
  "Hong Kong",
  "Isle of Man",
  "MS Zaandam",
  "Macao",
  "Martinique",
  "Mayotte",
  "Montserrat",
  "Myanmar",
  "New Caledonia",
  "Palestine",
  "Réunion",
  "Saint Martin",
  "Saint Pierre Miquelon",
  "Sint Maarten",
  "St. Barth",
  "Turks and Caicos Islands",
  "Wallis and Futuna",
  "Western Sahara",
];
